/**
 * Live Iceberg tables by metadata URI (spec 2026-09-28-0004 §2.2, LT-05,
 * LT-06, LT-08): a `remote: {kind: iceberg, metadataUri}` source stages its
 * candidate generation through the pinned trusted Iceberg capability with
 * true snapshot/delete semantics — never a raw read_parquet over the data
 * files. The authored versioned metadata JSON is a fixed pointer: Refresh
 * re-reads the same document and never chases a newer one; a failed refresh
 * retains the prior active generation with a visible source-specific error.
 *
 * The fixture is the hand-crafted Iceberg v2 table generated by
 * tests/fixtures/generate.py: one data file with rows A/B/C and a positional
 * delete file deleting B. The raw data file alone (what naive Parquet staging
 * would read) exposes three rows; the dashboard view must expose exactly the
 * two surviving rows.
 */

import { execFile } from "node:child_process";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import https from "node:https";
import os from "node:os";
import path from "node:path";
import { promisify } from "node:util";
import { pathToFileURL } from "node:url";
import { test } from "@playwright/test";
import { renderDashboard } from "../../scripts/build.mjs";
import {
 closeHarness,
 expect,
 requireInstalledDesktopChrome,
 rootDir,
} from "./helpers.mjs";

const execFileAsync = promisify(execFile);
const icebergDir = path.join(rootDir, ".artifacts", "fixtures", "iceberg");

/** Self-signed localhost certificate for the https S3-style fixture server. */
async function selfSignedLocalhostCert() {
 const dir = await mkdtemp(path.join(os.tmpdir(), "featherbi-iceberg-tls-"));
 const keyPath = path.join(dir, "key.pem");
 const certPath = path.join(dir, "cert.pem");
 try {
  await execFileAsync(
   "openssl",
   [
    "req",
    "-x509",
    "-newkey",
    "rsa:2048",
    "-keyout",
    keyPath,
    "-out",
    certPath,
    "-days",
    "1",
    "-nodes",
    "-subj",
    "/CN=127.0.0.1",
    "-addext",
    "subjectAltName=IP:127.0.0.1",
   ],
   { timeout: 30_000 },
  );
  return {
   key: await readFile(keyPath),
   cert: await readFile(certPath),
  };
 } finally {
  await rm(dir, { recursive: true, force: true });
 }
}

/**
 * Serve the generated Iceberg fixture as an S3-style bucket over https from
 * 127.0.0.1: object GET/HEAD with Range support and permissive CORS.
 * `control.failMetadata` fails only the authored v1 metadata document so a
 * refresh can fail after the first generation opened (LT-06), and
 * `requests` records every requested object key so the test can prove the
 * newer v2 metadata document is never fetched.
 */
async function serveIcebergBucket(tls, control = { failMetadata: false }) {
 const objects = new Map();
 for (const key of [
  "orders/data/00001.parquet",
  "orders/data/00001-delete.parquet",
  "orders/metadata/00001-m0.avro",
  "orders/metadata/00001-m1.avro",
  "orders/metadata/snap-555000001-00001.avro",
  "orders/metadata/snap-555000002-00001.avro",
  "orders/metadata/v1.metadata.json",
  "orders/metadata/v2.metadata.json",
 ]) {
  objects.set(
   key,
   await readFile(path.join(icebergDir, key.replace(/^orders\//, ""))),
  );
 }
 const server = https.createServer(
  { key: tls.key, cert: tls.cert },
  (request, response) => {
   response.setHeader("Access-Control-Allow-Origin", "*");
   response.setHeader(
    "Access-Control-Allow-Methods",
    "GET, HEAD, OPTIONS",
   );
   const allow = request.headers["access-control-request-headers"];
   response.setHeader("Access-Control-Allow-Headers", allow ?? "Range");
   response.setHeader(
    "Access-Control-Expose-Headers",
    "Content-Range, Accept-Ranges, Content-Length",
   );
   if (request.method === "OPTIONS") {
    response.writeHead(204);
    response.end();
    return;
   }
   const url = new URL(request.url, "https://s3.local");
   const key = url.pathname.replace(/^\/reports\//, "");
   control.requests.add(key);
   if (key === "orders/metadata/v1.metadata.json" && control.failMetadata) {
    response.writeHead(404, { "Content-Length": 0 });
    response.end();
    return;
   }
   const payload = objects.get(key);
   if (!payload) {
    response.writeHead(404, { "Content-Length": 0 });
    response.end();
    return;
   }
   if (request.method === "HEAD") {
    response.writeHead(200, {
     "Content-Length": payload.length,
     "Accept-Ranges": "bytes",
    });
    response.end();
    return;
   }
   const range = request.headers.range;
   if (range) {
    const match = /bytes=(\d*)-(\d*)/.exec(range);
    const start =
     match[1] === ""
      ? Math.max(0, payload.length - Number(match[2]))
      : Number(match[1]);
    const end =
     match[2] === "" || match[1] === ""
      ? payload.length - 1
      : Math.min(Number(match[2]), payload.length - 1);
    const body = payload.subarray(start, end + 1);
    response.writeHead(206, {
     "Content-Range": `bytes ${start}-${end}/${payload.length}`,
     "Content-Length": body.length,
     "Accept-Ranges": "bytes",
    });
    response.end(body);
    return;
   }
   response.writeHead(200, {
    "Content-Length": payload.length,
    "Accept-Ranges": "bytes",
   });
   response.end(payload);
  },
 );
 await new Promise((resolve) => server.listen(0, "127.0.0.1", resolve));
 return {
  origin: `https://127.0.0.1:${server.address().port}`,
  close: () => new Promise((resolve) => server.close(resolve)),
 };
}

/** One dashboard config declaring the Iceberg source. */
function icebergDashboardConfig({ auth, metadataUri }) {
 return {
  contract: 2,
  app: "grid",
  title: "Live iceberg table",
  data: {
   mode: "upload",
   sources: [
    {
     id: "orders",
     schema: {
      id: { type: "string", nullable: false },
      n: { type: "integer", nullable: false },
     },
     remote: { kind: "iceberg", metadataUri, auth },
    },
   ],
  },
  filters: [
   {
    id: "row",
    kind: "select",
    source: "orders",
    column: "id",
    default: null,
   },
  ],
  queries: {
   records: {
    sql: "SELECT count(*) AS records FROM orders WHERE ($row IS NULL OR id = $row)",
    params: ["row"],
   },
  },
  layout: [
   {
    id: "kpi_records",
    type: "kpi",
    query: "records",
    field: "records",
    label: "Orders",
    x: 1,
    y: 1,
    width: 12,
    height: 1,
   },
  ],
  theme: "neutral",
 };
}

async function writeDashboardPage(config, name) {
 const { html } = await renderDashboard({ config });
 const pagePath = path.join(rootDir, ".artifacts", "browser", name);
 await writeFile(pagePath, html, "utf8");
 return pagePath;
}

test.beforeAll(async ({ browser }) => {
 requireInstalledDesktopChrome(browser);
});

/**
 * LT-05/LT-08: the declared versioned metadata JSON is read through the
 * Iceberg reader with true snapshot/delete semantics. The raw data file
 * holds rows A/B/C (native fixture verification); the dashboard view must
 * exclude the positionally deleted row B — a raw Parquet staging would
 * report 3. The private prompt names the destination before entry (§4).
 */
test("an iceberg metadata-uri source reads its snapshot with delete semantics", async ({
 browser,
}) => {
 const tls = await selfSignedLocalhostCert();
 const control = { failMetadata: false, requests: new Set() };
 const fixture = await serveIcebergBucket(tls, control);
 const context = await browser.newContext({ ignoreHTTPSErrors: true });
 const page = await context.newPage();
 try {
  const config = icebergDashboardConfig({
   auth: "s3",
   metadataUri: "s3://reports/orders/metadata/v1.metadata.json",
  });
  config.data.sources[0].remote.endpoint = new URL(fixture.origin).host;
  const pagePath = await writeDashboardPage(config, "live-iceberg.html");
  await page.goto(pathToFileURL(pagePath).href, { waitUntil: "load" });

  // The private prompt shows the named metadata document and the effective
  // endpoint before credential entry (spec §4).
  await expect(
   page.locator("dialog [data-credential-destination]"),
  ).toContainText("s3://reports/orders/metadata/v1.metadata.json");
  await expect(
   page.locator("dialog [data-credential-destination]"),
  ).toContainText(new URL(fixture.origin).host);
  await page.locator('dialog input[aria-label="Key ID"]').fill("key-one");
  await page.locator('dialog input[aria-label="Secret"]').fill("secret-one");
  await page.locator('dialog button[type="submit"]').click();

  // The view applies the positional delete: 2 rows, not the raw file's 3.
  await expect(page.locator("#dashboard-status")).toHaveAttribute(
   "data-state",
   "ready",
  );
  await expect(page.locator("#component-kpi_records [data-value]")).toHaveText(
   "2",
  );
  // The deleted row is absent from the scan-backed filter options too.
  await expect(page.locator("#filter-row option")).toHaveText(["all", "A", "C"]);
  // Filtering reads the same pinned snapshot: exactly one A row survives.
  await page.locator("#filter-row").selectOption({ label: "A" });
  await page.locator("#apply-filters").click();
  await expect(page.locator("#component-kpi_records [data-value]")).toHaveText(
   "1",
  );
 } finally {
  await context.close();
  await fixture.close();
 }
});

/**
 * LT-05/LT-06: the authored metadata URI is a fixed pointer. A newer v2
 * metadata document exists in the bucket the whole time; Refresh re-reads
 * the SAME v1 document (never fetching v2) and results stay stable. A
 * refresh whose metadata document cannot be read keeps the prior active
 * generation usable with a source-specific error naming the source and
 * pointing at endpoint/CORS access, never packaged delivery.
 */
test("a fixed metadata URI stays pinned across Refresh and failures retain results", async ({
 browser,
}) => {
 const tls = await selfSignedLocalhostCert();
 const control = { failMetadata: false, requests: new Set() };
 const fixture = await serveIcebergBucket(tls, control);
 const context = await browser.newContext({ ignoreHTTPSErrors: true });
 const page = await context.newPage();
 try {
  const config = icebergDashboardConfig({
   auth: "none",
   metadataUri: "s3://reports/orders/metadata/v1.metadata.json",
  });
  config.data.sources[0].remote.endpoint = new URL(fixture.origin).host;
  const pagePath = await writeDashboardPage(
   config,
   "live-iceberg-refresh.html",
  );
  await page.goto(pathToFileURL(pagePath).href, { waitUntil: "load" });

  await expect(page.locator("#dashboard-status")).toHaveAttribute(
   "data-state",
   "ready",
  );
  await expect(page.locator("#component-kpi_records [data-value]")).toHaveText(
   "2",
  );
  // The Refresh control exists for iceberg sources (explicit refresh only).
  await expect(page.locator("#refresh-live")).toBeVisible();

  // A filtered read re-uses the pinned generation, not a new resolve.
  await page.locator("#filter-row").selectOption({ label: "C" });
  await page.locator("#apply-filters").click();
  await expect(page.locator("#component-kpi_records [data-value]")).toHaveText(
   "1",
  );

  // Explicit Refresh re-reads the SAME v1 document: the newer v2 metadata
  // (which would expose all three rows) is never fetched, results stable.
  control.requests.clear();
  await page.locator("#refresh-live").click();
  await expect(page.locator("#dashboard-status")).toHaveAttribute(
   "data-state",
   "ready",
  );
  await expect(page.locator("#component-kpi_records [data-value]")).toHaveText(
   "2",
  );
  expect([...control.requests]).toContain("orders/metadata/v1.metadata.json");
  expect([...control.requests]).not.toContain(
   "orders/metadata/v2.metadata.json",
  );

  // LT-06: a refresh whose metadata document cannot be read retains the
  // prior generation with a visible source-specific error; the remedy never
  // suggests packaged delivery for a live-only kind.
  control.failMetadata = true;
  await page.locator("#refresh-live").click();
  await expect(page.locator("#dashboard-status")).toHaveAttribute(
   "data-state",
   "error",
  );
  const failure = await page.locator("#dashboard-status").textContent();
  expect(failure).toContain("orders");
  expect(failure).toContain("Showing prior results");
  expect(failure).not.toContain("packaged build");
  await expect(page.locator("#component-kpi_records [data-value]")).toHaveText(
   "2",
  );

  // The retained generation keeps serving reads after the failed candidate
  // (and its staged secret) was cleaned up.
  control.failMetadata = false;
  await page.locator("#filter-row").selectOption({ label: "all" });
  await page.locator("#apply-filters").click();
  await expect(page.locator("#dashboard-status")).toHaveAttribute(
   "data-state",
   "ready",
  );
  await expect(page.locator("#component-kpi_records [data-value]")).toHaveText(
   "2",
  );

  // A later Refresh over the readable document succeeds again on the same
  // snapshot family.
  await page.locator("#refresh-live").click();
  await expect(page.locator("#dashboard-status")).toHaveAttribute(
   "data-state",
   "ready",
  );
  await expect(page.locator("#component-kpi_records [data-value]")).toHaveText(
   "2",
  );
  expect([...control.requests]).not.toContain(
   "orders/metadata/v2.metadata.json",
  );
 } finally {
  await context.close();
  await fixture.close();
 }
});
